version: 0.2
env:
  secrets-manager:
    DATABASE_URL: "${BUILD_ENV}/zerocore:DATABASE_URL"
    NODE_ENV:  "${BUILD_ENV}/zerocore:NODE_ENV"
    NEXTAUTH_SECRET:  "${BUILD_ENV}/zerocore:NEXTAUTH_SECRET"
    NEXTAUTH_URL: "${BUILD_ENV}/zerocore:NEXTAUTH_URL"
    OPENAI_API_KEY: "${BUILD_ENV}/zerocore:OPENAI_API_KEY"
    HOST:  "${BUILD_ENV}/zerocore:HOST"
    GEMINI_API_KEY: "${BUILD_ENV}/zerocore:GEMINI_API_KEY"
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install --global yarn
      - yarn install --frozen-lockfile --production=false
  pre_build:
    commands:
      # CHECK THAT THE SCHEMA IN THE DB MATCHES THE CURRENT CODE SCHEMA
      - npx prisma migrate diff --to-schema-datamodel ./prisma/schema.prisma --from-url $DATABASE_URL --exit-code
  build:
    commands:
      - yarn build
      - ls .next
  post_build:
    commands:
      - rm -rf node_modules
# post build 
artifacts:
  files:
    - '**/*'
    # - "package.json"
    # - "yarn.lock"
    # - "next.config.js"
    # - "public/**/*"
    # - ".next/**/*"
    # - "prisma/**/*"
    # - "nginx.conf"
    # - "scripts/**/*"
    # - "appspec.yml"



